name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Testes-automatizados/test-cypress-web

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Dar permissão no Cypress (bin)
        run: chmod +x ./node_modules/.bin/cypress

      - name: Instalar binário do Cypress
        run: ./node_modules/.bin/cypress install

      - name: Rodar Cypress (modo headless)
        run: ./node_modules/.bin/cypress run

      - name: Salvar vídeos e screenshots (em caso de falha)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
